version: '3.11.9'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/backend.dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
    networks:
      - paos-network

  frontend:
    build:
      context: .
      dockerfile: src/frontend.dockerfile
    container_name: frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - backend
    networks:
      - paos-network

networks:
  paos-network:
    external: true
