name: translator
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.11.9
  - ffmpeg
  - pip
  - pip:
      - torch==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - torchaudio==2.1.2+cu121
      - streamlit==1.44.1
      - audio_recorder_streamlit
      - requests
      - speechrecognition==3.10.1
      - pyngrok
      - python-dotenv
      - fastapi==0.115.5
      - uvicorn
      - git+https://github.com/openai/whisper.git
      - sentencepiece
      - numpy==1.26.4
      - python-multipart
      - langgraph==0.3.33
      - langchain-openai
      - langchain-huggingface
      - vllm==0.3.3
      - outlines==0.0.44
      - pydantic-settings
      - --extra-index-url https://download.pytorch.org/whl/cu121
